<mmd:mmd xmlns:mmd="http://www.met.no/schema/mmd" xmlns:gml="http://www.opengis.net/gml">
  <mmd:metadata_identifier>no.met:6f8befa6-2811-420f-b1e2-441deb32a5ec</mmd:metadata_identifier>
  <mmd:title xml:lang="en">dummy title</mmd:title>
  <mmd:abstract xml:lang="en">dummy summary</mmd:abstract>
  <mmd:metadata_status>Active</mmd:metadata_status>
  <mmd:dataset_production_status>Complete</mmd:dataset_production_status>
  <mmd:collection>METNCS</mmd:collection>
  <mmd:last_metadata_update>
    <mmd:update>
      <mmd:datetime>2023-03-31T07:40:13.595353Z</mmd:datetime>
      <mmd:type>Created</mmd:type>
    </mmd:update>
  </mmd:last_metadata_update>
  <mmd:temporal_extent>
    <mmd:start_date>2023-03-30T08:00:00Z</mmd:start_date>
    <mmd:end_date>2023-03-31T07:00:00Z</mmd:end_date>
  </mmd:temporal_extent>
  <mmd:iso_topic_category>climatologyMeteorologyAtmosphere</mmd:iso_topic_category>
  <mmd:iso_topic_category>environment</mmd:iso_topic_category>
  <mmd:iso_topic_category>oceans</mmd:iso_topic_category>
  <mmd:keywords vocabulary="GCMDSK">
    <mmd:keyword>EARTH SCIENCE &gt; ATMOSPHERE &gt; ATMOSPHERIC TEMPERATURE &gt; SURFACE TEMPERATURE &gt; AIR TEMPERATURE</mmd:keyword>
    <mmd:resource>https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords</mmd:resource>
    <mmd:separator></mmd:separator>
  </mmd:keywords>
  <mmd:geographic_extent>
    <mmd:rectangle srsName="EPSG:4326">
      <mmd:north>59.942300</mmd:north>
      <mmd:south>59.942300</mmd:south>
      <mmd:east>10.720000</mmd:east>
      <mmd:west>10.720000</mmd:west>
    </mmd:rectangle>
  </mmd:geographic_extent>
  <mmd:dataset_language>en</mmd:dataset_language>
  <mmd:use_constraint>
    <mmd:identifier>CC-BY-4.0</mmd:identifier>
    <mmd:resource>http://spdx.org/licenses/CC-BY-4.0</mmd:resource>
  </mmd:use_constraint>
  <mmd:personnel>
    <mmd:role>Investigator</mmd:role>
    <mmd:name>Not available</mmd:name>
    <mmd:email>Not available</mmd:email>
    <mmd:organisation>Not available</mmd:organisation>
  </mmd:personnel>
  <mmd:data_center>
    <mmd:data_center_name>
      <mmd:short_name>NO/MET</mmd:short_name>
      <mmd:long_name>Norwegian Meteorological Institute</mmd:long_name>
    </mmd:data_center_name>
    <mmd:data_center_url></mmd:data_center_url>
  </mmd:data_center>
  <mmd:related_dataset relation_type="parent">c14dd1a6-93f2-4959-b339-2fd03b692260</mmd:related_dataset>
  <mmd:storage_information>
    <mmd:file_name>latest.nc</mmd:file_name>
    <mmd:file_location>latest.nc</mmd:file_location>
    <mmd:file_format>NetCDF-CF</mmd:file_format>
    <mmd:file_size unit="MB">0.02</mmd:file_size>
  </mmd:storage_information>
  <mmd:related_information>
    <mmd:type>Dataset landing page</mmd:type>
    <mmd:description></mmd:description>
    <mmd:resource>https://met.no/</mmd:resource>
  </mmd:related_information>
  <mmd:spatial_representation>point</mmd:spatial_representation>
  <mmd:dataset_citation>
    <mmd:publication_date>2023-03-31T07:40:13.595353Z</mmd:publication_date>
    <mmd:title>dummy title</mmd:title>
  </mmd:dataset_citation>
</mmd:mmd>