@startuml "c4-container-elastic-data-store-event"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="micro service\neight sided")

Person(consumer, "Data Consumer")

System(its, "Ingest, Transform, Store", "The ITS system may have to enrich the metadata of some datasets, e.g., input BUFR files that are missing location metadata but contain the WIGOS identification.")

SystemQueue(queue, "Notification Service", "MQTT broker. WIS2 real-time data sharing by a publication/subscription (PubSub) mechanism.")

Container(replay, "Replay API", "", "API that allows access to historical events/notifications.", $tags = "microService")
Container(edr, "Search and Access APIs", "", "OGC EDR and OGC Records", $tags = "microService")
ContainerDb(eventstore, "Event Store", "JSON?", "Source of truth")
ContainerDb(db, "Data and metadata store", "PostGIS?", "Contains a view/projection of the (meta)data that is optimised for API queries.")
Container(bootstrap, "Bootstrap", "", "Used for initial load of (meta)data store from events")

Rel_R(its, eventstore, "add (meta)data", "JSON?")

Rel_R(eventstore, db, "ingest (meta)data", "")
Rel_R(eventstore, queue, "send notifications", "mqtt")
Rel_L(replay, eventstore, "request events", "")

Rel_D(bootstrap, replay, "request all events", "https")
Rel_D(bootstrap, db, "load (meta)data", "")

Rel_L(consumer, queue, "listen to notifications", "mqtt over websockets")
Rel_L(consumer, replay, "request missed notifications/events", "https")

Rel_L(edr, db, "search and access data", "JSON")
Rel_L(consumer, edr, "", "")

Lay_R(consumer, edr)
Lay_U(queue, db)
@enduml
