@startuml "E-SOH-C4-landscape-diagram"

!include <C4/C4_Container>

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' or use local:
'!include C4_Context.puml

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

title E-SOH C4 landscape diagram (C4 model: https://c4model.com/)

'AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="micro service\neight sided")


Person(consumer, "Data Consumer")

Enterprise_Boundary(femdi_all, "FEMDI") {
    System_Ext("femdigw", "FEMDI API gateway", "Central FEMDI API that gives access to all types of data (e.g., real-time station observations, radar, climate, warnings).")
}

Enterprise_Boundary(esoh_all, "E-SOH federated system"){
  System(centralapi, "Central E-SOH API end-point", "Central end-point linking the E-SOH local instances to provide a unified interface.")

  System_Boundary(esoh_fed, "E-SOH local instance"){
    System(esoh, "E-SOH local instance", "")
  }
}

' WIS2 box:
System_Boundary(wis2shared_all, "WIS2 shared services"){
    System_Ext(wis2shared, "WIS2.0 Shared Services", "Catalogue, Message Broker, Service manager, BUFR to GTS forwarding.")
    'System_Ext(wis2gts, "WMO WIS2.0 GTS relay", "Relay the BUFR files into GTS.")
}

System_Boundary(esoh_local_implementation, "Local E-SOH implementation"){
    System_Ext(obscoll_local,"Local Observations Collection", "NMHS Observation Collection system")
    System(esoh_local, "E-SOH local instance", "Same connections to other systems (e.g., Oscar) as the local component in the E-SOH federated system.")
}

SystemDb_Ext(oscar, "WMO OSCAR", "WMO WIGOS metadata DB")
System_Ext(obscoll,"Observations Collection", "NMHS Observation Collection system")

Rel_U(obscoll, esoh, "pushes data to")

Rel(obscoll_local, esoh_local, "pushes data to")


Rel(wis2shared, esoh, "listens to event queue, and gets BUFR data from")
Rel(esoh, oscar, "gets metadata from", "https")

Rel(consumer, wis2shared ,"query data")
Rel("consumer", "femdigw","query data")
Rel(femdigw, centralapi, "forwards data queries")
Rel(centralapi, esoh_local, "listens to event queue, and pulls data from")
Rel(centralapi, esoh, "listens to event queue, and pulls data from")

'layout:
'Lay_U("oscar", "obscoll")
'Lay_L("obscoll","esoh")

@enduml
